from __future__ import annotations
import logging
from pathlib import Path
from datetime import datetime
from jinja2 import Template
from svf.campaign.procedure import Verdict

logger = logging.getLogger(__name__)

REPORT_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>SVF Campaign Report — {{ record.campaign_id }}</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
         background: #f8fafc; color: #1e293b; padding: 2rem; }
  .header { margin-bottom: 2rem; }
  h1 { font-size: 1.5rem; font-weight: 700; margin-bottom: 0.25rem; }
  .meta { color: #64748b; font-size: 0.9rem; }
  .summary { display: grid; grid-template-columns: repeat(4, 1fr); gap: 1rem; margin-bottom: 2rem; }
  .card { background: white; border-radius: 8px; padding: 1.25rem; box-shadow: 0 1px 3px rgba(0,0,0,0.08); }
  .card-value { font-size: 2rem; font-weight: 700; }
  .card-label { font-size: 0.8rem; color: #64748b; }
  
  table { width: 100%; border-collapse: collapse; background: white; border-radius: 8px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.08); margin-bottom: 2rem; }
  th { background: #1e293b; color: white; text-align: left; padding: 0.75rem 1rem; font-size: 0.85rem; }
  td { padding: 1rem; border-bottom: 1px solid #f1f5f9; vertical-align: top; }
  
  .step-item { font-size: 0.85rem; margin-bottom: 0.4rem; padding-left: 1.2rem; position: relative; }
  .step-item::before { content: '✓'; position: absolute; left: 0; color: #22c55e; font-weight: bold; }
  .step-fail { color: #ef4444; }
  .step-fail::before { content: '✗'; color: #ef4444; }
  
  .badge { padding: 0.25rem 0.5rem; border-radius: 4px; font-weight: 700; font-size: 0.75rem; text-transform: uppercase; }
  .badge-pass { background: #f0fdf4; color: #22c55e; }
  .badge-fail { background: #fef2f2; color: #ef4444; }
  .badge-error { background: #fff7ed; color: #f97316; }
  .footer { color: #94a3b8; font-size: 0.8rem; margin-top: 2rem; text-align: center; }
</style>
</head>
<body>
  <div class="header">
    <h1>{{ record.campaign_name }}</h1>
    <div class="meta">
      Spacecraft: <strong>{{ record.spacecraft }}</strong> | Generated: {{ timestamp }} | Duration: {{ "%.1f"|format(record.duration_s) }}s
    </div>
  </div>

  <div class="summary">
    <div class="card"><div class="card-value">{{ record.n_procedures }}</div><div class="card-label">Procedures</div></div>
    <div class="card"><div class="card-value" style="color:#22c55e">{{ record.n_pass }}</div><div class="card-label">PASS</div></div>
    <div class="card"><div class="card-value" style="color:#ef4444">{{ record.n_fail }}</div><div class="card-label">FAIL</div></div>
    <div class="card"><div class="card-value">{{ "%.1f"|format(record.pass_rate * 100) }}%</div><div class="card-label">Success Rate</div></div>
  </div>

  <h2>Procedure Results</h2>
  <table>
    <thead>
      <tr>
        <th style="width: 15%">ID / Req</th>
        <th style="width: 25%">Title</th>
        <th style="width: 10%">Verdict</th>
        <th>Execution Trace & Invariants</th>
      </tr>
    </thead>
    <tbody>
    {% for r in record.results %}
      <tr>
        <td>
            <strong>{{ r.procedure_id }}</strong><br>
            <span style="font-family: monospace; font-size: 0.8rem; color: #64748b">{{ r.requirement }}</span>
        </td>
        <td>{{ r.title }}</td>
        <td>
            <span class="badge badge-{{ r.verdict.value.lower() }}">{{ r.verdict.value }}</span>
            <div style="font-size: 0.7rem; color: #94a3b8; margin-top: 4px">{{ "%.1f"|format(r.duration_s) }}s</div>
        </td>
        <td>
            {% for step in r.steps %}
            <div class="step-item {{ 'step-fail' if step.verdict.value == 'FAIL' else '' }}">
                <strong>{{ step.step_name }}</strong>
                {% if step.detail %}<div style="color: #64748b; font-size: 0.8rem; margin-top: 2px">{{ step.detail }}</div>{% endif %}
            </div>
            {% endfor %}
            {% if r.error and not r.steps %}
                <div style="color: #ef4444; font-size: 0.85rem">Error: {{ r.error }}</div>
            {% endif %}
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>

  <div class="footer">
    Generated by OpenSVF | <a href="https://github.com/lipofefeyt/opensvf" style="color:#94a3b8">github.com/lipofefeyt/opensvf</a>
  </div>
</body>
</html>"""

class CampaignReporter:
    def generate(self, report, output_path: Path) -> Path:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        template = Template(REPORT_TEMPLATE)
        html = template.render(
            record=report,
            timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        )
        output_path.write_text(html)
        return output_path

def generate_html_report(report, output_path: Path) -> Path:
    """Standalone function expected by the CLI."""
    reporter = CampaignReporter()
    return reporter.generate(report, output_path)
