from __future__ import annotations
import logging
from pathlib import Path
from datetime import datetime
from jinja2 import Template
from svf.campaign.procedure import Verdict

# Type checking imports
from typing import TYPE_CHECKING, Dict, List, Any
if TYPE_CHECKING:
    from svf.campaign.campaign_runner import CampaignReport

logger = logging.getLogger(__name__)

# We use a simplified but clean template that MUST contain the string "Requirement Coverage"
REPORT_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>SVF Report</title>
<style>
    body { font-family: sans-serif; background: #f8fafc; color: #1e293b; padding: 2rem; }
    .summary { display: flex; gap: 1rem; margin-bottom: 2rem; }
    .card { background: white; padding: 1rem; border-radius: 8px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); flex: 1; }
    table { width: 100%; border-collapse: collapse; background: white; margin-bottom: 2rem; }
    th { background: #1e293b; color: white; text-align: left; padding: 0.75rem; }
    td { padding: 0.75rem; border-bottom: 1px solid #e2e8f0; vertical-align: top; }
    .badge { padding: 0.25rem 0.5rem; border-radius: 4px; font-weight: bold; font-size: 0.8rem; }
    .badge-pass { background: #dcfce7; color: #166534; }
    .badge-fail { background: #fee2e2; color: #991b1b; }
    .event { font-size: 0.8rem; color: #64748b; font-family: monospace; }
</style>
</head>
<body>
    <h1>{{ record.campaign_name or "Campaign Report" }}</h1>
    <p>Spacecraft: {{ record.spacecraft }} | Date: {{ timestamp }}</p>

    <div class="summary">
        <div class="card"><strong>Procedures:</strong> {{ record.n_procedures }}</div>
        <div class="card"><strong>Pass:</strong> {{ record.n_pass }}</div>
        <div class="card"><strong>Fail:</strong> {{ record.n_fail }}</div>
    </div>

    <h2>Procedure Results</h2>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Requirement</th>
                <th>Verdict</th>
                <th>Execution Trace</th>
            </tr>
        </thead>
        <tbody>
            {% for r in record.results %}
            <tr>
                <td>{{ r.procedure_id }}</td>
                <td>{{ r.requirement }}</td>
                <td><span class="badge badge-{{ r.verdict.value.lower() }}">{{ r.verdict.value }}</span></td>
                <td>
                    {% for step in r.steps %}
                        <div><strong>{{ step.step_name }}</strong></div>
                        {% for ev in step.events %}
                            <div class="event">[{{ ev.t }}s] {{ ev.event_type }}: {{ ev.description }}</div>
                        {% endfor %}
                    {% endfor %}
                    {% if r.error %}<div style="color:red">{{ r.error }}</div>{% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <h2>Requirement Coverage</h2>
    <table>
        <thead>
            <tr>
                <th>Requirement ID</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            {% for req_id, status in req_summary.items() %}
            <tr>
                <td>{{ req_id }}</td>
                <td><span class="badge badge-{{ 'pass' if status == 'COVERED' else 'fail' }}">{{ status }}</span></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <p class="footer">Generated by OpenSVF</p>
</body>
</html>"""

class CampaignReporter:
    def generate(self, report: CampaignReport, output_path: Path) -> Path:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        
        # Build requirement summary for the table
        req_summary: Dict[str, str] = {}
        for r in report.results:
            if r.requirement:
                # If we haven't seen it, or if it previously passed but now fails, update it
                current = req_summary.get(r.requirement, "COVERED")
                if r.verdict != Verdict.PASS:
                    req_summary[r.requirement] = "FAILED"
                else:
                    req_summary[r.requirement] = current

        template = Template(REPORT_TEMPLATE)
        html = template.render(
            record=report,
            req_summary=req_summary,
            timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        )
        output_path.write_text(html)
        return output_path

def generate_html_report(report: CampaignReport, output_path: Path) -> Path:
    return CampaignReporter().generate(report, output_path)
